name: "Release"

on:
  push:
    branches: [ release ]
  pull_request:

jobs:

  release:
    name: Release
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/release'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Use Cache 
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-release

    - name: Install Dependencies
      run: yarn install

    - name: Get Package Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - uses: "marvinpinto/action-automatic-releases@v1.1.2"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.package-version.outputs.current-version}}"
        prerelease: false

    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
